version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/requirements"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 5
    reviewers:
      - "jvaguiar05"
    assignees:
      - "jvaguiar05"
    commit-message:
      prefix: "deps"
      include: "scope"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 3
    reviewers:
      - "jvaguiar05"
    assignees:
      - "jvaguiar05"
    commit-message:
      prefix: "ci"
      include: "scope"