# Generated by Django 5.2.6 on 2025-09-12 21:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlotStatusEvents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('event_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('event_type', models.CharField(choices=[('STATUS_CHANGE', 'Mudança de Status'), ('VEHICLE_DETECTED', 'Veículo Detectado'), ('VEHICLE_LEFT', 'Veículo Saiu'), ('MAINTENANCE_START', 'Início de Manutenção'), ('MAINTENANCE_END', 'Fim de Manutenção'), ('RESERVATION_START', 'Início de Reserva'), ('RESERVATION_END', 'Fim de Reserva')], max_length=50)),
                ('occurred_at', models.DateTimeField()),
                ('sequence', models.BigIntegerField(blank=True, null=True)),
                ('prev_status', models.CharField(blank=True, max_length=16, null=True)),
                ('curr_status', models.CharField(max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('source_model', models.CharField(blank=True, max_length=60, null=True)),
                ('source_version', models.CharField(blank=True, max_length=30, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'slot_status_events',
            },
        ),
    ]
