# Generated by Django 5.2.6 on 2025-09-12 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotstatusevents',
            name='camera',
            field=models.ForeignKey(blank=True, db_column='camera_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slot_status_events', to='hardware.cameras'),
        ),
    ]
