# Generated by Django 5.2.6 on 2025-09-12 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('events', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotstatusevents',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.clients'),
        ),
        migrations.AddField(
            model_name='slotstatusevents',
            name='curr_vehicle',
            field=models.ForeignKey(blank=True, db_column='curr_vehicle_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curr_slot_status_events', to='catalog.vehicletypes'),
        ),
        migrations.AddField(
            model_name='slotstatusevents',
            name='lot',
            field=models.ForeignKey(db_column='lot_id', on_delete=django.db.models.deletion.PROTECT, related_name='slot_status_events', to='catalog.lots'),
        ),
        migrations.AddField(
            model_name='slotstatusevents',
            name='prev_vehicle',
            field=models.ForeignKey(blank=True, db_column='prev_vehicle_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prev_slot_status_events', to='catalog.vehicletypes'),
        ),
        migrations.AddField(
            model_name='slotstatusevents',
            name='slot',
            field=models.ForeignKey(db_column='slot_id', on_delete=django.db.models.deletion.PROTECT, related_name='slot_status_events', to='catalog.slots'),
        ),
        migrations.AddIndex(
            model_name='slotstatusevents',
            index=models.Index(fields=['slot', 'occurred_at'], name='ix_slot_sts_events_occ_at'),
        ),
    ]
