# Generated by Django 5.2.6 on 2025-09-12 21:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('key_id', models.CharField(max_length=64, unique=True)),
                ('hmac_secret_hash', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='CameraHeartbeats',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'camera_heartbeats',
            },
        ),
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('camera_code', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('UNASSIGNED', 'Não atribuída'), ('ASSIGNED', 'Atribuída'), ('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa'), ('MAINTENANCE', 'Manutenção'), ('ERROR', 'Erro')], default='UNASSIGNED', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cameras',
            },
        ),
    ]
