# Generated by Django 5.2.6 on 2025-09-12 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKeys',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('key_id', models.CharField(max_length=64, unique=True)),
                ('hmac_secret_hash', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.clients')),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('camera_code', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('UNASSIGNED', 'Não atribuída'), ('ASSIGNED', 'Atribuída'), ('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa'), ('MAINTENANCE', 'Manutenção'), ('ERROR', 'Erro')], default='UNASSIGNED', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.ForeignKey(db_column='api_key_id', on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='hardware.apikeys')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.clients')),
                ('establishment', models.ForeignKey(blank=True, db_column='establishment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='catalog.establishments')),
                ('lot', models.ForeignKey(blank=True, db_column='lot_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='catalog.lots')),
            ],
            options={
                'db_table': 'cameras',
            },
        ),
        migrations.CreateModel(
            name='CameraHeartbeats',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('camera', models.ForeignKey(db_column='camera_id', on_delete=django.db.models.deletion.PROTECT, related_name='heartbeats', to='hardware.cameras')),
            ],
            options={
                'db_table': 'camera_heartbeats',
            },
        ),
        migrations.AddConstraint(
            model_name='cameras',
            constraint=models.UniqueConstraint(fields=('client', 'camera_code'), name='uq_cameras_client_code'),
        ),
        migrations.AddIndex(
            model_name='cameraheartbeats',
            index=models.Index(fields=['camera', 'received_at'], name='ix_cam_heartbeats_cam_rec_at'),
        ),
    ]
