# Generated by Django 5.2.6 on 2025-09-12 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('hardware', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikeys',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.clients'),
        ),
        migrations.AddField(
            model_name='cameras',
            name='api_key',
            field=models.ForeignKey(db_column='api_key_id', on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='hardware.apikeys'),
        ),
        migrations.AddField(
            model_name='cameras',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.clients'),
        ),
        migrations.AddField(
            model_name='cameras',
            name='establishment',
            field=models.ForeignKey(blank=True, db_column='establishment_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='catalog.establishments'),
        ),
        migrations.AddField(
            model_name='cameras',
            name='lot',
            field=models.ForeignKey(blank=True, db_column='lot_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cameras', to='catalog.lots'),
        ),
        migrations.AddField(
            model_name='cameraheartbeats',
            name='camera',
            field=models.ForeignKey(db_column='camera_id', on_delete=django.db.models.deletion.PROTECT, related_name='heartbeats', to='hardware.cameras'),
        ),
        migrations.AddConstraint(
            model_name='cameras',
            constraint=models.UniqueConstraint(fields=('client', 'camera_code'), name='uq_cameras_client_code'),
        ),
        migrations.AddIndex(
            model_name='cameraheartbeats',
            index=models.Index(fields=['camera', 'received_at'], name='ix_cam_heartbeats_cam_rec_at'),
        ),
    ]
