# Generated by Django 5.2.6 on 2025-09-12 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'slot_types',
            },
        ),
        migrations.CreateModel(
            name='StoreTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'store_types',
            },
        ),
        migrations.CreateModel(
            name='VehicleTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'vehicle_types',
            },
        ),
        migrations.CreateModel(
            name='Establishments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.clients')),
                ('store_type', models.ForeignKey(blank=True, db_column='store_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='catalog.storetypes')),
            ],
            options={
                'db_table': 'establishments',
            },
        ),
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lot_code', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.clients')),
                ('establishment', models.ForeignKey(db_column='establishment_id', on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.establishments')),
            ],
            options={
                'db_table': 'lots',
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('slot_code', models.CharField(max_length=10)),
                ('polygon_json', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.clients')),
                ('lot', models.ForeignKey(db_column='lot_id', on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='catalog.lots')),
                ('slot_type', models.ForeignKey(db_column='slot_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='catalog.slottypes')),
            ],
            options={
                'db_table': 'slots',
            },
        ),
        migrations.CreateModel(
            name='SlotStatusHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('event_id', models.UUIDField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(db_column='slot_id', on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='catalog.slots')),
                ('vehicle_type', models.ForeignKey(blank=True, db_column='vehicle_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slot_status_history', to='catalog.vehicletypes')),
            ],
            options={
                'db_table': 'slot_status_history',
            },
        ),
        migrations.CreateModel(
            name='SlotStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('FREE', 'Livre'), ('OCCUPIED', 'Ocupada'), ('RESERVED', 'Reservada'), ('MAINTENANCE', 'Manutenção'), ('DISABLED', 'Desabilitada')], max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('slot', models.ForeignKey(db_column='slot_id', on_delete=django.db.models.deletion.PROTECT, related_name='current_status', to='catalog.slots')),
                ('vehicle_type', models.ForeignKey(blank=True, db_column='vehicle_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slot_statuses', to='catalog.vehicletypes')),
            ],
            options={
                'db_table': 'slot_status',
            },
        ),
        migrations.AddConstraint(
            model_name='lots',
            constraint=models.UniqueConstraint(fields=('client', 'lot_code'), name='uq_lots_client_code'),
        ),
        migrations.AddConstraint(
            model_name='slots',
            constraint=models.UniqueConstraint(fields=('lot', 'slot_code'), name='uq_slots_lot_code'),
        ),
        migrations.AddIndex(
            model_name='establishments',
            index=models.Index(fields=['store_type'], name='ix_establishments_store_type'),
        ),
        migrations.AddConstraint(
            model_name='establishments',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='uq_establishments_client_name'),
        ),
        migrations.AddIndex(
            model_name='slotstatushistory',
            index=models.Index(fields=['slot', 'recorded_at'], name='ix_slot_hist_slot_rec_at'),
        ),
        migrations.AddConstraint(
            model_name='slotstatus',
            constraint=models.UniqueConstraint(fields=('slot',), name='uq_slot_status_slot'),
        ),
    ]
