# Generated by Django 5.2.6 on 2025-09-12 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishments',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.clients'),
        ),
        migrations.AddField(
            model_name='lots',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.clients'),
        ),
        migrations.AddField(
            model_name='lots',
            name='establishment',
            field=models.ForeignKey(db_column='establishment_id', on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='catalog.establishments'),
        ),
        migrations.AddField(
            model_name='slots',
            name='client',
            field=models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='tenants.clients'),
        ),
        migrations.AddField(
            model_name='slots',
            name='lot',
            field=models.ForeignKey(db_column='lot_id', on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='catalog.lots'),
        ),
        migrations.AddField(
            model_name='slotstatus',
            name='slot',
            field=models.ForeignKey(db_column='slot_id', on_delete=django.db.models.deletion.PROTECT, related_name='current_status', to='catalog.slots'),
        ),
        migrations.AddField(
            model_name='slotstatushistory',
            name='slot',
            field=models.ForeignKey(db_column='slot_id', on_delete=django.db.models.deletion.PROTECT, related_name='status_history', to='catalog.slots'),
        ),
        migrations.AddField(
            model_name='slots',
            name='slot_type',
            field=models.ForeignKey(db_column='slot_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='catalog.slottypes'),
        ),
        migrations.AddField(
            model_name='establishments',
            name='store_type',
            field=models.ForeignKey(blank=True, db_column='store_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='catalog.storetypes'),
        ),
        migrations.AddField(
            model_name='slotstatushistory',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, db_column='vehicle_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slot_status_history', to='catalog.vehicletypes'),
        ),
        migrations.AddField(
            model_name='slotstatus',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, db_column='vehicle_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='slot_statuses', to='catalog.vehicletypes'),
        ),
        migrations.AddConstraint(
            model_name='lots',
            constraint=models.UniqueConstraint(fields=('client', 'lot_code'), name='uq_lots_client_code'),
        ),
        migrations.AddConstraint(
            model_name='slots',
            constraint=models.UniqueConstraint(fields=('lot', 'slot_code'), name='uq_slots_lot_code'),
        ),
        migrations.AddIndex(
            model_name='establishments',
            index=models.Index(fields=['store_type'], name='ix_establishments_store_type'),
        ),
        migrations.AddConstraint(
            model_name='establishments',
            constraint=models.UniqueConstraint(fields=('client', 'name'), name='uq_establishments_client_name'),
        ),
        migrations.AddIndex(
            model_name='slotstatushistory',
            index=models.Index(fields=['slot', 'recorded_at'], name='ix_slot_hist_slot_rec_at'),
        ),
        migrations.AddConstraint(
            model_name='slotstatus',
            constraint=models.UniqueConstraint(fields=('slot',), name='uq_slot_status_slot'),
        ),
    ]
