# Generated by Django 5.2.6 on 2025-09-12 20:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('onboarding_status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('SUSPENDED', 'Suspenso'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=32)),
            ],
            options={
                'db_table': 'clients',
                'indexes': [models.Index(fields=['name'], name='ix_clients_name')],
            },
        ),
        migrations.CreateModel(
            name='ClientMembers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.PROTECT, related_name='client_members', to='identity.roles')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='client_members', to='identity.users')),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.PROTECT, related_name='client_members', to='tenants.clients')),
            ],
            options={
                'db_table': 'client_members',
                'constraints': [models.UniqueConstraint(fields=('client', 'user'), name='uq_client_members_client_user')],
            },
        ),
    ]
