# Generated by Django 5.2.6 on 2025-09-17 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("catalog", "0002_initial"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="clientmembers",
            name="uq_client_members_client_user",
        ),
        migrations.AddField(
            model_name="clientmembers",
            name="establishment",
            field=models.ForeignKey(
                blank=True,
                db_column="establishment_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="client_members",
                to="catalog.establishments",
            ),
        ),
        migrations.AddConstraint(
            model_name="clientmembers",
            constraint=models.UniqueConstraint(
                fields=("client", "user", "establishment", "role"),
                name="uq_client_members_unique",
            ),
        ),
    ]
